<a href="https://colab.research.google.com/github/LukeSpinosa/Machine_learning/blob/main/HW_1_Question_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Question #2
# You can repetativly run this using the 2 different methods while they remain
# consistantly equal proving the 2 methods produce the same output
import torch

def ex2_transform(w, x, b, method='affine'):
    if method == 'affine':
        result = torch.mm(x.T, w) + b
    else:
        ones_row = torch.ones(1, x.shape[1])
        x_extended = torch.cat((x, ones_row), 0)
        w_extended = torch.cat((w, torch.tensor([[b]])), 0)

        result = torch.mm(x_extended.T, w_extended)

    print(f"result_by_{method}:\n", result)
    return result

w = torch.tensor([[1.], [2.], [3.], [4.]])  # weight mat
x = torch.randn(4, 5)  # input mat
b = 3.  # bias term

k = 1 # Just keeping track of the loops
while k < 5:
    print(f"Test # {k}")
    affine_method = ex2_transform(w, x, b, 'affine')
    linear_method = ex2_transform(w, x, b, 'linear')
    if torch.all(affine_method.eq(linear_method)):
        print("EQUAL")
    else:
        print("NOT equal")
    print("-------------------------")
    k = k + 1

Test # 1
result_by_affine:
 tensor([[11.1281],
        [ 2.6149],
        [-4.7311],
        [ 5.1141],
        [-3.4300]])
result_by_linear:
 tensor([[11.1281],
        [ 2.6149],
        [-4.7311],
        [ 5.1141],
        [-3.4300]])
EQUAL
-------------------------
Test # 2
result_by_affine:
 tensor([[11.1281],
        [ 2.6149],
        [-4.7311],
        [ 5.1141],
        [-3.4300]])
result_by_linear:
 tensor([[11.1281],
        [ 2.6149],
        [-4.7311],
        [ 5.1141],
        [-3.4300]])
EQUAL
-------------------------
Test # 3
result_by_affine:
 tensor([[11.1281],
        [ 2.6149],
        [-4.7311],
        [ 5.1141],
        [-3.4300]])
result_by_linear:
 tensor([[11.1281],
        [ 2.6149],
        [-4.7311],
        [ 5.1141],
        [-3.4300]])
EQUAL
-------------------------
Test # 4
result_by_affine:
 tensor([[11.1281],
        [ 2.6149],
        [-4.7311],
        [ 5.1141],
        [-3.4300]])
result_by_linear:
 tensor([[11.1281],
        [ 2.6149],
      